---
title: "Planning des cours et tarifs"
description: "Horaires et tarifs des cours de barre au sol, jazz et renforcement musculaire."
---


Plusieurs formats de cours sont proposés :

- [Cours collectif tous publics](#cours_collectifs)
- [Cours sur Zoom](#cours_zoom)
- [Cours en entreprise](#cours_entreprise)
- [Cours particulier](#cours_particulier)

## Cours collectifs tous publics {#cours_collectifs}

Cours de barre au sol au Studio Cambronne, nombre de places limité.

- lundi à 20h
- mardi à 20h


Tarif à l'unité 19€

Abonnement annuel 640€ soit 40 cours à 16€ le cours et **place garantie toute l'année**.



<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2625.601448525861!2d2.2948280154248675!3d48.846740409481356!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47e670178c1c5dfd%3A0xcdeddcd81b7dd27f!2s71%20Rue%20Fondary%2C%2075015%20Paris!5e0!3m2!1sen!2sfr!4v1646055588981!5m2!1sen!2sfr" width="100%" height="450" style="border:0;" allowfullscreen="" loading="lazy"></iframe>

## Cours sur Zoom {#cours_zoom}

Cours réguliers sur Zoom 

- dimanche 10h30

Tarif 10€

## Cours en entreprise {#cours_entreprise}

Cours en entreprise via Zoom ou dans les locaux, par l'intermédiaire de l'association sportive de l'entreprise.

- L'ANSM : 2 types de cours proposés 1) barre au sol 2) renforcement musculaire + stretching
- Le Sénat : 2 types de cours proposés 1) modern-jazz 2) renforcement musculaire + stretching)

**N'hésitez pas à me contacter pour que je vienne donner des cours dans votre entreprise**

## Cours particulier {#cours_particulier}

Possibilité de cours particuliers flexibles ou réguliers de barre au sol ou renforcement musculaire + stretching.

Les cours ont lieu sur Zoom ou chez vous selon votre préférence.

Tarif 60€ sur place et 50€ sur Zoom.

[Me contacter](contact) par email ou téléphone pour plus d'informations.

## Modes de paiement

- Par chèque
- Par virement bancaire
- En espèce pour les cours présentiels

Facture sur demande pour prise en charge par votre comité d'entreprise.

