---
title: "Marine Olivari Professeur de Danse"
description: "Cours de barre au sol avec Marine Olivari Paris 15ème 75015"
output:
  rmdformats::material:
    use_bookdown: true
    self_contained: true
    default_style: "light"
    downcute_theme: "default"
---


```{r setup, include=FALSE}
## Global options
knitr::opts_chunk$set(cache = TRUE)
```

# Accueil {#accueil}

Bienvenue sur le site de [Marine Olivari](#education).

Je donne des cours de danse Modern-Jazz et de [barre au sol](#floorbarre), mais également des cours de renforcement musculaire et stretching pour adultes de tous niveaux.

Les cours collectifs ont lieu sur Zoom ou au [studio Cambronne situé 71 Rue Fondary, 75015 Paris](https://www.studiocambronne.com/enseignants/marine_olivari.html).

Je donne aussi des cours particuliers sur demande, [me contacter](#contact)

Rendez-vous sur l'onglet [Horaires et tarifs](#contact) trouver l'ensemble des horaires et tarifs pour mes cours réguliers.


# Barre au sol {#floorbarre}

La barre au sol permet de travailler le muscle en longueur et en profondeur. La position au sol permet de s’affranchir des contraintes d’équilibre et de gestion du poids du corps pour se concentrer sur le placement, les directions et la respiration.

Le cours commence toujours par 15 minutes d’échauffement pour préparer le corps afin de solliciter les bons groupes musculaires durant les exercices.

Le cours se poursuit avec plusieurs répétitions de mouvements issus de la danse classique dans les positions assise, allongée, jambes en l’air (90°) et sur le ventre.

Cette structure de cours s’inspire de la méthode Boris Kniaseff, créateur de la barre au sol.

Ce que j’essaie de valoriser dans mon cours, c’est une pratique tous niveaux où les débutants peuvent travailler les formes, les mouvements et le placement de la danse classique, tandis que des pratiquants plus avancés vont pouvoir peaufiner leur technique, la qualité et la précision du mouvement, la coordination, la force et la souplesse.
 

La barre au sol s’apparente à la danse, tout le cours se fait en musique et j’utilise différents styles musicaux, adaptés aux exercices pour travailler la musicalité du mouvement.


# Horaires et tarifs des cours {#horaires}

Je propose 4 formats de cours : 


- Cours collectif tous publics
- Cours sur Zoom
- Cours en entreprise
- Cours particulier

## Cours collectifs tous publics

Cours de barre au sol au Studio Cambronne

- mardi à 20h
- jeudi à 19h30

Tarif 15€

<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2625.601448525861!2d2.2948280154248675!3d48.846740409481356!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47e670178c1c5dfd%3A0xcdeddcd81b7dd27f!2s71%20Rue%20Fondary%2C%2075015%20Paris!5e0!3m2!1sen!2sfr!4v1646055588981!5m2!1sen!2sfr" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy"></iframe>

## Cours sur Zoom

Cours réguliers sur Zoom 


- jeudi 19h30
- dimanche 10h15

Tarif 10€

## Cours en entreprise

Cours en entreprise via Zoom ou dans les locaux, par l'intermédiaire de l'association sportive de l'entreprise.

- L'ANSM : 2 types de cours proposés 1) barre au sol 2) renforcement musculaire + stretching
- Le Sénat : 2 types de cours proposés 1) modern-jazz 2) renforcement musculaire + stretching)
- Le Figaro : barre au sol

**N'hésitez pas à me contacter pour que je vienne donner des cours dans votre entreprise**

## Cours particulier

Possibilité de cours particuliers flexibles ou réguliers de barre au sol ou renforcement musculaire + stretching.

Les cours ont lieu sur Zoom ou chez vous selon votre préférence.

Tarif 50€

[Me contacter](contact) par email ou téléphone pour plus d'informations.

## Règlement

- Par chèque
- Par virement bancaire
- En espèce pour les cours présenciels


# Formation {#education}

**Professeure de danse diplômée d’État depuis 2007, Marine Olivari a suivi sa formation à l’école Epsedanse de Montpellier.**

Après plusieurs années de pratique intensive de la danse, j’ai découvert la barre au sol ce qui fût une révélation dans mon approche de la danse et de la pédagogie.

# Contact

Vous pouvez me contacter :

- par SMS ou téléphone au 06.63.06.18.30
- par email à [marineolivari@hotmail.com](mailto:marineolivari@hotmail.com)





